version: '2'

services:
    fhem:
        restart: always
        ports:
            - "8083:8083"
            - "7072:7072"
        image: ghcr.io/fhem/fhem/fhem-docker:bullseye
        volumes:
            - "./fhem/:/opt/fhem/"
        devices:
            - "/dev/lesekopf:/dev/lesekopf"
        networks:
            - fhem-network
        environment:
            FHEM_UID: 1000
            FHEM_GID: 1000
            TIMEOUT: 10
            RESTART: 1
            TELNETPORT: 7072
            TZ: Europe/Berlin
        depends_on:
            postgres:
                 condition: service_healthy


    postgres:
        restart: always
        expose:
            - "5432"
        ports:
            - "5432:5432"
        image: postgres:13-bullseye
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=fhem
            - POSTGRES_USER=fhem
            - POSTGRES_PASSWORD=fhem
            - SHARED_BUFFERS=256MB
            - EFFECTIVE_CACHE_SIZE=512MB
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U fhem"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - fhem-network

volumes:
    pgdata:

networks:
    fhem-network:
        driver: bridge
