services:
    fhem:
        restart: always
        ports:
            - "1883:1883"
            - "8083-8085:8083-8085"
            - "7072:7072"
        image: ghcr.io/fhem/fhem/fhem-minimal-docker:bullseye
        volumes:
            - "./fhem/:/opt/fhem/"
        devices:
            - "/dev/lesekopf:/dev/lesekopf"
        networks:
            - fhem-network
        environment:
            FHEM_UID: 1000
            FHEM_GID: 1000
            TIMEOUT: 10
            RESTART: 1
            TELNETPORT: 7072
            TZ: Europe/Berlin
            APT_PKGS: "wakeonlan"
        depends_on:
            postgres:
                 condition: service_healthy


    postgres:
        restart: always
        expose:
            - "5432"
        ports:
            - "5432:5432"
        image: postgres:13-bullseye
        # Scripts in /docker-entrypoint-initdb.d are only run if you start the container with a data
        # directory that is empty; any pre-existing database will be left untouched on container startup.
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        # Access to the database from the other container needs to reference the container name as the host;
        # localhost won't work; dblog.conf for FHEM was changed accordingly
        environment:
            - POSTGRES_DB=fhem
            - POSTGRES_USER=fhem
            - POSTGRES_PASSWORD=fhem
            - SHARED_BUFFERS=128MB
            - EFFECTIVE_CACHE_SIZE=256MB
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U fhem"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - fhem-network

    homebridge:
        image: oznu/homebridge:ubuntu
        restart: always
        network_mode: host
        volumes:
          - ./homebridge:/homebridge
        environment:
          - PGID=1000
          - PUID=1000
          - HOMEBRIDGE_CONFIG_UI=1
          - HOMEBRIDGE_CONFIG_UI_PORT=8581
          - TZ=Europe/Berlin
        depends_on:
            fhem:
                 condition: service_healthy

volumes:
    pgdata:

networks:
    fhem-network:
        driver: bridge
